---
title: "Projects"
page-layout: full
toc: false
---

Climate change in coastal lomas along the Atacama Desert. Octubre 2022 to the present.
Project coordinator.

---

Climate change on the Southern coast of Peru: Analysis of impacts on ecosystems and
community perspectives. 2024-2026. Project coordinator.

---

Functional traits in spiders across an altitudinal gradient in coastal lomas. 2023-2025.
Thesis co-advisor.

---

Vertebrates occurences in Chilean Peruvian coastal lomas 2023-2025. Project
coordinator.

---

Diversitty patters in coastal lomas ecosystems in South America, Marzo 2018 to the
present. Project coordinator.

---

Efecto de dos estadios sucesionales (vegetación clímax ¨pacal¨ y sucesión primaria
¨purma¨) en la comunidad de roedores presentes en la estación biológica Villa Carmen,
Kosnipata, Cusco – Investigador Principal, investigación realizada con la beca de
ACCA y Fundación Erol, Mayo 2016 – Noviembre 2016 (terminado). Project
coordinator.

---

Proyecto de Evaluación del estado de Conservación de Myrcianthes ferreyrae en las
lomas costeras de Arequipa- Marzo 2012 a Noviembre 2014. Project coordinator.
Proyecto de Ecología de Restauración Forestal en Ancash- 10 al 17 de Julio 2014- Field
assistant.

---