---
title: "Abstracts at conferences"
page-layout: full
toc: false
---

## Abstracts at Conferences

Gonzales, F.N. (2012).  
**Alcances sobre la cacería de mamíferos silvestres en el Parque Nacional Tingo María.**  
III Congreso de la Sociedad Peruana de Mastozoología (14–18 de octubre de 2012).

---

Gonzales, F.N. & Llerena, G. (2012).  
**Estudio preliminar de patrones de actividad en cautiverio y respuestas al enriquecimiento ambiental del oso andino (*Tremarctos ornatus*) en el Zoológico Zoo Mundo, 2010.**  
III Congreso de la Sociedad Peruana de Mastozoología (14–18 de octubre de 2012).

---

Llerena, G., Gonzales, F.N., Pumacota, M. & López, E. (2014).  
**Evaluación del conflicto entre el puma y la ganadería en un área protegida de la zona altoandina del sur del Perú.**  
Simposio Internacional *Conservación de Felinos en América*, Costa Rica, 23–26 de mayo de 2014.

---

Llerena, G., Gonzales, F.N., Pumacota, M., Jove, C., Quispe, R. & López, E. (2014).  
**Situación actual del puma (*Puma concolor*) en el sur del Perú: Implicancias para su conservación.**  
Simposio Internacional *Conservación de Felinos en América*, Costa Rica, 23–26 de mayo de 2014.

---

Llerena, G., Gonzales, F.N., Pumacota, M., Jove, C., Quispe, R. & López, E. (2014).  
**Aportes al estado de conocimiento de dos pequeños felinos en los Andes del sur del Perú.**  
Simposio Internacional *Conservación de Felinos en América*, Costa Rica, 23–26 de mayo de 2014.




