---
title: "Papers"
page-layout: full
toc: false
---

## Publicaciones científicas

Zeballos, H., Pari, A., Medina, C. E., Pino, K., Arias, S., Arce, A. L., & Gonzales, F. N. (2025).  
**Description of a New Genus and Species of Semi-Aquatic Rodent (Cricetidae, Sigmodontinae, Ichthyomyini) from the Southern Peruvian Andes.**  
*Diversity*, 17(6), 406.  
[https://doi.org/10.3390/d17060406](https://doi.org/10.3390/d17060406)

---

Gonzales FN, Craven D, Arapa L & H. Keft. (2024).  
**Unravelling an inverse latitudinal gradient: Environmental and geographical drivers on plant diversity in South American coastal lomas.**  
*bioRxiv* (pre-print).  
[https://doi.org/10.1101/2024.10.23.619859](https://doi.org/10.1101/2024.10.23.619859)

---

Halbritter, A.H., Vandvik, V., Cotner, S.H. *et al.* (2024).  
**Plant trait and vegetation data along a 1314 m elevation gradient with fire history in Puna grasslands, Perú.**  
*Scientific Data*, 11, 225.  
[https://doi.org/10.1038/s41597-024-02980-3](https://doi.org/10.1038/s41597-024-02980-3)

---

Gonzales FN, Craven D, Armesto J. (2023).  
**Islands in the mist: A systematic review of the coastal lomas of South America.**  
*Journal of Arid Environments*, 211.  
[https://doi.org/10.1016/j.jaridenv.2023.104942](https://doi.org/10.1016/j.jaridenv.2023.104942)

---

Gonzales Guillén, FN., &amp; Villasante Benavides, F. (2019). Estado de conservación de
Myrcianthes ferreyrae un árbol endémico de las lomas costeras del sur del Perú. Revista
Peruana De Biología, 26(2), 235-242.
https://doi.org/10.15381/rpb.v26i2.16380

---

Gonzales Guillén, F. N., & Villasante Benavides, F. (2019).  
**Estado de conservación de Myrcianthes ferreyrae, un árbol endémico de las lomas costeras del sur del Perú.**  
*Revista Peruana De Biología*, 26(2), 235-242.  
[https://doi.org/10.15381/rpb.v26i2.16380](https://doi.org/10.15381/rpb.v26i2.16380)

---

Gonzales FN. Arce A y Zeballos H. (2017). New range extension of the rare peruvian fish-eating
rat Neusticomys peruviensis Musser and Gardner, 1974 (rodentia: cricetidae) in Peru. Revista
Peruana de Biologia 24(4): 413-416. oi: [http://dx.doi.org/10.15381/rpb.v24i4.14068](http://dx.doi.org/10.15381/rpb.v24i4.14068)

---

Gonzales, F., Neira-Llerena, J., Llerena, G., &amp; Zeballos, H. (2016). Pequeños vertebrados en la
dieta del oso andino (Tremarctos ornatus Cuvier, 1825) en el norte del Perú. Revista Peruana
De Biologia, 23(1), 61 - 66. doi:[http://dx.doi.org/10.15381/rpb.v23i1.11834](http://dx.doi.org/10.15381/rpb.v23i1.11834)

---

Málaga E, Llerena G, Gonzales F, Mamani N. (2016) Nuevo registro de la ocurrencia simpátrica
de subespecies de bandurria de cara negra (Theristicus melanopis) en la costa sur de Perú.
Libro de resúmenes del X Congreso Nacional de Ornitología.
[http://www.xcnochachapoyas2016.com/libro-de-resumenes-delxcno/](http://www.xcnochachapoyas2016.com/libro-de-resumenes-delxcno/)

---

Gonzales F N &amp; Reátegui G. (2013). Cacería de mamíferos en la Zona de Uso Especial y de
Amortiguamiento del Parque Nacional Tingo María, Huánuco, Perú. Revista
Peruana de Biología 21(3): 283 –286. [http://dx.doi.org/10.15381/rpb.v21i3.10904](http://dx.doi.org/10.15381/rpb.v21i3.10904)

---

Gonzales F. 2014. Myrcianthes ferreyrae. The IUCN Red List of Threatened Species
2014:e.T60492231A60492909.[http://dx.doi.org/10.2305/IUCN.UK.20143.RLTS.T60492231A60](http://dx.doi.org/10.2305/IUCN.UK.20143.RLTS.T60492231A60)
492909.en.

---

Gonzales F. 2013.-Evaluación del estado de conservación de Myrcianthes ferreyrae (Mc Vaught
1958) “arrayan” en las lomas de Atiquipa, Taymara y Chala Viejo (Caraveli-Arequipa). Tesis
para obtener el título profesional de Biólogo, Universidad Nacional de San Agustín. (no
publicada).

---

Gonzales F, Llerena G, Villazante F. 2013. Alcances sobre el estado de conservación de
Mycianthes ferreyrae (Mc Vaught, 1958) especie arbórea y endémica de Perú. En el libro de
resúmenes de la Red Peruana de Investigadores Ambientales (RedPeAl).

---

Llerena G &amp; Gonzales FN. 2012.Presencia de perros ferales en la Reserva Nacional Salinas y
Aguada Blanca, Arequipa, Perú en Libro de Resúmenes del II Congreso Latinoamericano de
Mastozoología.

---

Llerena. G, Gonzales. F, Palle. S, Villalba. K, Flores, E. 2010.-Filogenia del género (Artibeus
Leach 1872), basado en caracteres morfológicos externos. Libro de Resúmenes del XI
Congreso de estudiantes de Biología.

---

Llerena. G, Gonzales, F &amp; Concha. R. 2010. Evaluación del conflicto entre carnívoros y
ganadería en los anexos de Mosopuquio (Characato) y Caccayaco (Chiguata). Arequipa – Perú.
Rev. Dilloniana Edición Especial, pag: 142.